---
title: "GGPLOT2"
author: "Gustavo Bertrán"
date: "2025-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(ggpmisc)
```

```{r}
my.formula = y ~ x
ggplot(msleep,
       aes(x = log(bodywt),
           y = sleep_total,
           color = vore)) +
  geom_point() + 
  geom_smooth(method = "lm",
              se = FALSE) +
  scale_color_manual(
    values = c(
      "herbi" = "green",
      "carni" = "red",
      "omni" = "blue",
      "insecti" = "orange",
      "unknown" = "gray"
      )
  ) +
  stat_poly_eq(formula = my.formula,
               parse = TRUE,
               label.y = "top",
               label.x = "left",
               use_label(c("eq","R2","P")))+
  facet_wrap(. ~ vore,
             ncol = 2,
             scales = "free") + 
  theme_bw(16)
```

```{r}
library(dplyr)
library(ggpubr)
msleep2 <- msleep %>% 
  mutate(logbodywt = log10(bodywt))
ggscatter(msleep2,
          x = "logbodywt",
          y = "sleep_total",
          add = "reg.line",
          conf.int = TRUE,
          cor.coef = TRUE,
          cor.method = "pearson",
          xlab = "Log10 Body Weight",
          ylab = "Total Sleep (hours)"
          )
```

```{r}
setwd("~/Intro R/Project R/R-Studio-Workarounds/assignments")
library(dplyr)
library(ggplot2)
library(ggpubr)
library(readxl)
library(ggpmisc)
library(ggbeeswarm)
library(broom)
library(ggstatsplot)
theme_set(theme_bw(16))

msleep <- read.csv("msleep.csv")
```


```{r}
my.formula = y ~ x
ggplot(msleep,
       aes(x = log(bodywt),
           y = sleep_total,
           color = vore)) +
  geom_point() + 
  geom_smooth(method = "lm",
              se = FALSE) +
  scale_color_manual(
    values = c(
      "herbi" = "green",
      "carni" = "red",
      "omni" = "blue",
      "insecti" = "orange",
      "unknown" = "gray"
      )
  ) +
  stat_poly_eq(formula = my.formula,
               parse = TRUE,
               label.y = "top",
               label.x = "left",
               use_label(c("eq","R2","P")))+
  facet_wrap(. ~ vore,
             ncol = 2,
             scales = "free") + 
  theme_bw(16) +
  theme(
    strip.background = element_rect(fill = "steelblue", color = "black",
                                    size = 1),
    strip.text = element_text(color = "white", face = "bold", size = 14)
    
  )
```

